export const USER_LOGIN_IN = 'USER_LOGIN_IN'; //用户登陆
export const USER_LOGIN_OUT = 'USER_LOGIN_OUT'; //用户登陆
export const USER_LOGIN_REGISTER = 'USER_LOGIN_REGISTER'; //用户注册
export const INDEX_NOVEL_RECOMMEND = 'INDEX_NOVEL_RECOMMEND';
export const SET_COVER_NOVEL_LIST = 'SET_COVER_NOVEL_LIST';  //主页的小说推荐
export const SET_RANK_LIST_TYPE = 'SET_RANK_LIST_TYPE'; //小说排行种类
export const SET_RANK_LIST = 'SET_RANK_LIST'; //小说排行
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST'; // 小说类别列表
export const CATE_LIST_PAGING_ADD = 'CATE_LIST_PAGING_ADD'; //小说类别列表分页增加
export const CATE_LIST_PAGING_MINUS = 'CATE_LIST_PAGING_MINUS'; //小说类别列表分页减
export const SET_WHOLE_NOVEL_LIST = 'SET_WHOLE_NOVEL_LIST'; //全本小说查询
export const SET_NIVEL_DETAIL = 'SET_NIVEL_DETAIL'; //获取但本小说信息
export const SET_NOVEL_CHAPTER = 'SET_NIVEL_CHAPTER'; //根据章节ID查询章节
export const SET_CHAPTER_DETAIL = 'SET_CHAPTER_DETAIL'; //查询章节详细信息